services:
  - type: redis
    name: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
  - type: web
    name: server
    runtime: image
    plan: free
    image:
      url: docker.io/erikbrudzinskis/fibonacci-server:master
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis
          property: port
      - key: PGHOST
        fromDatabase:
          name: postgres
          property: connectionString
      - key: PGPORT
        fromDatabase:
          name: postgres
          property: port
  - type: web
    name: worker
    runtime: image
    plan: free
    image:
      url: docker.io/erikbrudzinskis/fibonacci-worker:master
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis
          property: port
  - type: web
    name: client
    runtime: image
    plan: free
    image:
      url: docker.io/erikbrudzinskis/fibonacci-client:master
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis
          property: port
  - type: web
    name: nginx
    runtime: image
    plan: free
    image:
      url: docker.io/erikbrudzinskis/fibonacci-nginx:master
databases:
  - name: postgres
    plan: free