name: Deploy
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v3
        working-directory: ./client
        run: |
          npm install
          npm run test

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./client/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/fibonacci-client
          - dockerfile: ./nginx/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/fibonacci-nginx
          - dockerfile: ./server/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/fibonacci-server
          - dockerfile: ./worker/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/fibonacci-worker
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}